### ISSUE TITLE
Language seems to default to en

### ISSUE THREAD

**Issue by emaxmax** [writeas/writefreely#129]
### Describe the bug
It seems that the language metadata is always "en", even if the text is not obviously.
I checked that with the API `/api/posts/`

### Steps to reproduce (if necessary)
1. Create a post, not in english
2. Check the language with the API
3. Maybe check also the language in the ActivityPub message (don't have debug tools to do it myself)

### Expected behavior

If no language is specified by the user, use the "und" value specified in ActivityStreams: https://www.w3.org/TR/activitystreams-core/#naturalLanguageValues 
As a new feature: offer the UX to the user to specify the post language, on a post or blog basis.

### Application configuration
 - **Single mode or Multi-user mode?**  Multi
 - **Open registration?**  yes
 - **Federation enabled?** yes

**Version or last commit**: 0.9.1-104-g541c3a9

**Comment by thebaer** [comment]
Thanks for looking into this. But the language setting isn't derived from the text. When publishing via the web application, we detect the language from your browser settings and use that to set the language of the post: https://github.com/writeas/writefreely/blob/bb0be02b4f877b4573d91b5b55b2255dcf9dc403/templates/pad.tmpl#L150

Our other official clients do something similar, trying to determine the language from the user's system if possible. Of course this isn't perfect, but it solves most cases. If the language isn't correct, a user can always change the post's language via the API, or in the web app:

1. Publish a post
1. Click "edit"
1. Click the small "i" icon near the top right of the editor
1. Select a different language

Let me know if I missed something. But I'll close this for now since it doesn't seem to be a bug.

**Comment by emaxmax** [comment]
Thanks for the hint.
It's ok for me, but I still think that for average users, a UX during the writing would be better than one after.
But that's your design, I'm fine with the current solution!
