### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by matusvictormatus** [writeas/writefreely#135]
Hello, could you be so kind as to also build and release your great software for ARMv7 (which is what most single-board computers have on them):

In the readme is mention that 

> It's easy to install and light enough to run on a Raspberry Pi

However in the releases there's no arm option and the [tutorial](https://write.as/buttpicker/the-expected-tutorial-how-to-install-writefreely-on-a-raspberry-pi-3-in-10) (as it states itself), only works for versions below 0.6.

**Comment by thebaer** [comment]
Yep, that's a great point. I've added an ARMv7 build [for v0.10](https://github.com/writeas/writefreely/releases/tag/v0.10.0), and we'll continue doing that going forward.

(On this note, we'll release builds for all possible architectures starting with v1.0.)

**Comment by diazepan** [comment]
I wrote an updated tutorial in spanish
https://blog.pueseso.club/el-nuevo-tutorial-como-instalar-writefreely-en-una-raspberry-pi-3-ahora-en-13

What changes is the following:
1) You have to install go 1.11+ (the installation uses the 1.11 modules), go-bindata, nodejs and the modules "less" and "less-plugin-clean-css"

2) Execute "env GOARCH=arm GOARM=7 GO111MODULE=on go build github.com/writeas/writefreely/cmd/writefreely". It will fail because you have to compile the assets but this is for downloading the sources

3) In the go/pkg/mod/github.com/writeas/writefreely/ directory, execute "make ui" and "make assets"

4) Execute again "env GOARCH=arm GOARM=7 GO111MODULE=on go build github.com/writeas/writefreely/cmd/writefreely" and this time will work

**Comment by matusvictormatus** [comment]
> Yep, that's a great point. I've added an ARMv7 build [for v0.10](https://github.com/writeas/writefreely/releases/tag/v0.10.0), and we'll continue doing that going forward.
> 
> (On this note, we'll release builds for all possible architectures starting with v1.0.)

I have had it running since the day you released it and everything seems to be working a-ok on raspbian, thank you very much!
