### ISSUE TITLE
Support for other databases

### ISSUE THREAD

**Issue by lupine** [writeas/writefreely#14]
Is there interest in adding sqlite, boltdb/bbolt, or postgres  support to writefreely? The first two, in particular, are well-placed for use with small deployments and lower the setup barrier significantly.

I'm happy to contribute code for this, but since it implies additional maintenance burden, I thought I'd check to see if it'd be welcome first!

**Comment by thebaer** [comment]
Definitely! I'd particularly like to get sqlite in there in the short-term, especially because I think it'll be the most manageable. As long as you're okay with signing the contributor's agreement [mentioned here](https://github.com/writeas/writefreely/blob/master/CONTRIBUTING.md#contributing-code), please feel free to start on that!

**Comment by lupine** [comment]
Ah, that's a shame. I wouldn't mind a DCO, but I see very little point contributing AGPL code along with a CLA - from my perspective, it would be better for it to be MIT or a similar license from the outset. Thanks for the heads-up.

**Comment by thebaer** [comment]
Sure thing, thanks for the input!
