### ISSUE TITLE
Leverage a demo user for writefreely to decrease lingering user accounts

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#150]
Running  a writefreely instance for a while shows that many users just register to have a short look at writefreely and then never post anything. This is of course fine, but creates quite a bit of 'noise-data'.

If we could leverage a 'demo' user and enourage visitors to use that before registering, this would have a number of advantages:

- casual exploration of the system is even easier than it is now
- we could provide some content for them to look at to get familiar with the system and prefill an installed instance with 'showcase content' (probably refreshed at certain intervals, this could be as simple as some sql-script running under cron-like control)
- the number of users and posts will be qualitatively better on sites like https://the-federation.info
- it's easier to support users of the system by using an account both user and administrator can use to work something out.

Alternatively, at least allow users to delete their created account, but perhaps that should be a additional issue.

**Comment by thebaer** [comment]
Thanks for the input! I like the idea of a demo account, or some temporary way for people to try out an instance.

Let's continue discussing this idea [on the forum](https://discuss.write.as/t/leverage-a-demo-user-for-writefreely-to-decrease-lingering-user-accounts/764), where we discuss other feature requests. Closing the issue here since it isn't a bug.
