### ISSUE TITLE
Potential case-insensitive import collision

### ISSUE THREAD

**Issue by unknwon** [writeas/writefreely#156]
Due to GitHub handle change (to lowercase) for long term purpose, `go get` may fail fetching `github.com/Unknwon/com`. 
Please consider take some time to update it to `github.com/unknwon/com` in the `go.mod` file.
I truly apology for the inconvenience and unintended troubles caused.

**Comment by robjloranger** [comment]
No problem, and thanks for the heads up @unknwon 
I'll update our imports.

**Comment by robjloranger** [comment]
Looks like our only use is indirect, so hopefully the package authors that import it directly update their projects.

**Comment by thebaer** [comment]
Haven't verified, but I'm guessing the [github.com/gogs/gogs](https://github.com/gogs/gogs) repo we use imports the package.

**Comment by unknwon** [comment]
Ah, right. Just curious the gogs/gogs repo is not meant to be imported, what’s being used here?

**Comment by thebaer** [comment]
Just checked -- we're actually importing `github.com/gogits/gogs/pkg/tool` in `admin.go` to output application data: https://github.com/writeas/writefreely/blob/8557119451f49638e69dc128a0842bd09e7dc9c9/admin.go#L404-L440

Looking at it now, we can probably just implement those funcs on our own instead of importing everything.

**Comment by unknwon** [comment]
[A little copying is better than a little dependency.](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s) 🤣

**Comment by thebaer** [comment]
@robjloranger feel free to tackle this next -- just need to copy over the needed funcs and use them instead.
