### ISSUE TITLE
Collection.hostName is empty in the logs

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#161]
No UI behaviour mishap as far as I can see.

Upgrading to revision `8557119451f49638e69dc128a0842bd09e7dc9c9` on `develop` this line starts showing up in the logs and instructs to file a bug.

**Comment by thebaer** [comment]
Thanks -- which requests do you see this on?

**Comment by mrvdb** [comment]
all of them

**Comment by thebaer** [comment]
Sharing any particular ones would be a huge help :)

**Comment by mrvdb** [comment]
Not sure what I can add, the root at https://qua.name gives the error (4 times) Clicking on any blog (logged in), same. 

A specific post, say https://qua.name/mrb/federated-writing-start doesn't show the error.

Editting a post does show it (https://qua.name/info/example-page/edit)

**Comment by mrvdb** [comment]
In general: it seems only authenticated requests cause the error.

**Comment by thebaer** [comment]
Thanks, that helps narrow it down. Will take a look.

**Comment by robjloranger** [comment]
Found the issue here, there is no host name on any collection. not even in the DB schemas

So will need to update the schemas and write a migration, or change `c.Hostname` to a function that returns either the collection hostname if set or the configured app hostname otherwise.

**Comment by thebaer** [comment]
Ah, that's not quite it... We don't want to store the `hostName` in the DB -- it's configured in `config.ini`. The problem is that we're manually setting it in various places, like this one: https://github.com/writeas/writefreely/blob/8557119451f49638e69dc128a0842bd09e7dc9c9/collections.go#L450-L454

so that we don't have to pass in the app configuration into every database func. And we've missed a spot -- `viewCollections()` is one of those spots.

**Comment by robjloranger** [comment]
oh ok, so only manual. much easier :grin:
