### ISSUE TITLE
changing username weirdly affects federation

### ISSUE THREAD

**Issue by wakest** [writeas/writefreely#226]
I just noticed that you can change your username on writefreely and thought that was quite strange since its the first software I have noticed in the fediverse that has this ability. If I am following a writefreely account from mastodon and I change my username, I am not automatically following the new username, and I am still following the old one. so if I change my username 10 times I can separately follow 10 different accounts. I am unsure of all the repercussions of this but I can think of many. I think at the very least there should be a warning that changing the username is *not recommended* due to some incompatibilities or issues with federation between other parts of the fediverse.

was playing with the new instance https://scream.today (running writefreely v0.11.2)

**Comment by thebaer** [comment]
Hey, thanks for bringing this up! Yeah, we've always let people change their username, from before we added ActivityPub support. In my experience, it's pretty important for usability, so I wouldn't want to remove that feature. But I think your suggestion of adding a warning would be great -- whether that's in the app or just in the [documentation](https://github.com/writefreely/documentation).

Otherwise we'll need other fediverse platforms to agree on how they follow changed usernames. That could be `301` redirects on our end, as suggested in [this SocialHub thread](https://socialhub.activitypub.rocks/t/is-objects-id-immutable/381), or maybe something else.

For the WriteFreely side, let's continue this discussion on [this Discuss thread](https://discuss.write.as/t/warn-user-about-changing-username-on-federated-instances/1008) and on SocialHub. I'll close this issue now since it's more of a feature request than a bug.
