### ISSUE TITLE
Language metadata gets reset to English after editing a post

### ISSUE THREAD

**Issue by cjeller1592** [writeas/writefreely#280]
Brought up originally on [the forum](https://discuss.write.as/t/language-metadata-gets-reset-to-english-after-re-publishing-a-post/1183):

>Normally, after setting a language for a post, it should stick and should not change unless the author modifies it again. However if you edit the post and (re)publish it again it causes the language field to reset back to English.

### Steps to reproduce
1. Go to a post and click 'Edit.' Go into the metadata and change the Language to something else and save your changes. Publish the post.
2. Now edit the post again, this time the body of the post, and publish.
3. Go back to the metadata of the post. Note how it is now 'English.'

### Expected behavior
Post should keep the metadata language after edited, not revert to English.

**Comment by thebaer** [comment]
Thanks for copying that over. Off the top of my head, this happens because we include the `lang` parameter every time we publish or update a post, which passes along the browser's default language (which is likely English in this user's case).

The fix should be simple: in `templates/pad.tmpl`, only pass `lang` when initially creating a post. When editing / updating a post, don't pass the `lang` parameter.

**Comment by vince2bir** [comment]
For information, I write in french but all my apps and browser are setup in english.
It might be nice to have a choice in the "customize" page of a blog to leave it as-is or overide it to a language of our choice.

**Comment by agyild** [comment]
I have already written in the forum but it's been nearly year since this issue was reported. I think at this point it would be better if one of the active developers implemented this fix if it is so simple instead of waiting for a new contributor.
