### ISSUE TITLE
federation with Misskey links to wrong endpoint

### ISSUE THREAD

**Issue by wakest** [writeas/writefreely#291]
I am following my Writefreely blog from my Misskey account, and posts federated into misskey link to the wrong api endpoint. This may be something wrong with MIsskey's side, but I thought you might be easier to report this to since they don't speak much english.

you can see the Writefreely post I am referring to loaded into Misskey here
https://misskey.io/notes/85kd93y85t

**Version or last commit**:
writefreely v0.11.2

**Comment by cjeller1592** [comment]
Yeah I think this is something on Misskey's side. I just made an issue on their repo if you want to follow it: https://github.com/syuilo/misskey/issues/6213

Thanks for bringing this up!

**Comment by cjeller1592** [comment]
So it looks like Misskey resolved & closed the issue on their end: https://github.com/syuilo/misskey/issues/6213

Federation with Misskey should be fixed as soon as they push these changes. I will close the issue here @wakest but feel free to open it again if their pushed changes haven't solved the problem.
