### ISSUE TITLE
Nodeinfo counts collections instead of users, intentional?

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#354]
The information wf provides at the /api/nodeinfo endpoint has the number of collections in the `users` key instead of the user count.

While the patch to correct this is fairly easy, I get the feeling this was on purpose, so before I submit a PR for this, was it indeed intentional to count collections? And if so, why.

The same goes for the 6month statistics query, which counts posts on collections, not active users.

**Comment by thebaer** [comment]
Yes this was intentional, for a few reasons:

* Protecting privacy -- publicly, each blog / collection looks like a separate user. This is so you can have a single account on a WF instance but write under multiple pseudonyms without readers knowing it's the same author behind each blog.
* Technically, each blog is a unique "user" / actor in the fediverse.

I'm open to any thoughts you have here, but as far as public stats go, I think the current design is right and consistent with our privacy model. If admins ever need to see an accurate number, they can find that in the Admin Dashboard, or of course limit blogs to 1 per user.

I'll close this issue, but feel free to continue the discussion here or on [the forum](https://discuss.write.as).

**Comment by mrvdb** [comment]
Crystal clear, thanks.

The only minor inconsistency that is left then is that the notion of an internal user as seen on the admin panel is different from an external user as presented in the nodeinfo. A rename to 'account' is an option, but I feel this would be too intrusive for such a small inconsistency.

**Comment by thebaer** [comment]
Yeah, that's a good point. I'm thinking it'll be worth it to clarify this in the documentation, and then if it comes up again we can figure out how we might update the application.
