### ISSUE TITLE
About/Privacy Page don't source their footer template from custom template folder

### ISSUE THREAD

**Issue by luroc** [writeas/writefreely#400]
### Describe the bug
There is a slight chance that I introduced this bug myself as I am running a custom executable, but I am pretty sure I didn't touch that part of the code.

The About and Privacy page sources it's template from the default template folder, although a custom template folder is given.

### Steps to reproduce (if necessary)
1. Define a custom template folder
2. Change the {custom template}/templates/include/footer.tmpl
3. About and Privacy page still use the footer from /templates/include/footer.tmpl

### Expected behavior
The About and Privacy Page should use the footer.tmpl from the custom template folder

### Application configuration
 - Multi-user mode
 - mysql
 - **Open registration?** yes
 - **Federation enabled?** yes

**Version or last commit**:
Custom build based on 12.0

**Comment by thebaer** [comment]
Hi! Thanks for reaching out, but this question is better suited for a **support channel**, rather than our **bug tracker**. WriteFreely wasn't built to support custom templates like this, and we don't provide support for custom code here, so I'll close this since it isn't a bug in the software.

The best way to resolve this would be to [ask our community](https://discuss.write.as/c/development/7), or have us help with your project through our [paid development services](https://write.as/writefreely).

Either way, if you get this working, you could always submit a pull request with your custom code, and help us add support for custom templates!
