### ISSUE TITLE
draft posts are visible on site by their id

### ISSUE THREAD

**Issue by mrvdb** [writeas/writefreely#415]
I get a fair bit of abuse on our instance by people who register an account but never actually publish anything. Every post they create (typically a few lines with a link to some poker/money/sex site) is left in drafts.

The link to the draft post  is visible though.

An example:  https://qua.name/scow1bj3v2

This makes life as an instance admin harder than it needs to be.

**Comment by thebaer** [comment]
Thanks for the report. So just to be sure, the draft post is still visible when one of these users is _silenced_?

**Comment by mrvdb** [comment]
I think the silencing does not make a difference, but I'm not 100% sure. I will test that again.  

You're not implying that for a non-silenced user the draft should be visible are you?

**Comment by mrvdb** [comment]
Tested quickly, it's only when a user is not silenced that drafts are visible

**Comment by thebaer** [comment]
Yeah, drafts are meant to be optionally shareable, which is why they're available at secret but publicly-accessible URLs. So this is working as designed.

While it's unconventional for blogging platforms, I think this approach enables much more flexible uses, while keeping things simple. Plus if someone needs truly private drafts, they could create a new blog and set it to Private. But maybe this doesn't make as much sense anymore? Could be worth [starting a discussion](https://discuss.write.as/c/writefreely/15) about it.

**Comment by mrvdb** [comment]
I don't understand what value it adds for legitimate users in the current setup. I'll implement a local solution for this for now. Thx
