### ISSUE TITLE
Setting host with subpath doesn't work

### ISSUE THREAD

**Issue by thegergo02** [writeas/writefreely#422]
### Describe the bug
The service is behind an nginx reverse proxy which tries to use a subpath, like this:
```
location /writefreely/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_pass http://127.0.0.1:8080/
    proxy_redirect off;
}
```
Even if I set the
```
[app]
host = https://example.com/writefreely
```
Every link redirects to `https://example.com/[actual path]` instead of `https://example.com/writefreely/[actual path]`

### Steps to reproduce (if necessary)
1. `systemctl start nginx`
2. `systemctl start writefreely`
3. Go to `example.com/writefreely`
4. Get greeted with the login page
5. Click on any link
6. Get routed to a bad path as described above

### Expected behavior
I get redirected to `https://example.com/writefreely/[actual path]`

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user mode
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: v0.12.0

**Comment by thegergo02** [comment]
I just realised the pages are making the request from JS and they all point use root. Maybe a prefix setting could be a solution? If I can figure it out I might do a PR.

**Comment by thegergo02** [comment]
...or I might just redirect every request that WriteFreely can make with nginx.

**Comment by thegergo02** [comment]
Both of these ways are quite hacky and I don't really want to use them. I noticed that static resources actually follow the path I want, so those show up correctly.

**Comment by thebaer** [comment]
Thanks for starting this discussion! It's true that WF was never designed to work on a path, so indeed this custom configuration is going to be an uphill battle. If you'd like to see this built in to the software, please feel free to start a discussion on our [development forum](https://discuss.write.as/c/development/7) so we can figure out what needs to be done and coordinate any work on this!

**Comment by rouilj** [comment]
Was a discussion on this ever opened? I was also trying to put it under a path from my main web domain (at /blog) and had no luck when I found this issue.

**Comment by ernstki** [comment]
> Was a discussion on this ever opened? I was also trying to put it under a path from my main web domain (at /blog) and had no luck when I found this issue.

@rouilj see [this discuss.write.as thread](https://discuss.write.as/t/install-writefreely-with-apache-and-mysql/665) for one such discussion. It's not as straightfoward as it seems to just bodge this with some Apache mod_rewrite rules.

Taking [Caddy](https://caddyserver.com/docs/quick-starts/reverse-proxy) as an example, you can [read this](https://caddy.community/t/rewrite-local-services-static-url-to-subpath/21654) to gain an understanding of the issues. Basically, your app either

- has to support running from a subpath off the root (@thebaer has repeatedly said WF does not support this, so it's likely a volunteer would have to add such support in a PR)
- or else you have to have to rewrite the request body, so that, for example, `/css/icons.css` is replaced with `/blog/css/icons.css`

There is apparently [a module for Caddy](https://github.com/caddyserver/replace-response) for doing the latter, if you happen to be using Caddy and can be bothered to compile in the module.

Good luck!
