### ISSUE TITLE
Time/Date issue

### ISSUE THREAD

**Issue by misaka00251** [writeas/writefreely#51]
### Describe the bug
So I'm in UTC+8, and I want to edit the post's time.
Assume now my local time is `2018-10-04 17:43:00`.
First, type the time and click save.
Then for a few seconds, it changes the time to `2018-10-04 09:43:00` (minus 8 hours) and have a UTC outside the label.
Then the page refreshed, and now it said the time is `2018-10-05 01:43:00` (plus another 8 hours).

### Steps to reproduce (if necessary)
1. Post or edit any posts.
2. Change the date.

### Expected behavior
Save my local time `2018-10-04 17:43:00`.

### Application configuration
 - **Single mode** 

**Version or last commit**: 0.6.0

**Comment by thebaer** [comment]
This happens because the app assumes your database timezone is set to UTC. So when updating post metadata, on the client-side it converts the time you supply into UTC (which you can see) and then stores that in the database.

I could see a solution going one of two ways:

* The app supports databases set to any time zone. Presumably, this would be for installs on personal computers, instead of servers. This potentially causes issues in locales that observe daylight savings time, or while traveling and changing timezones.
* We add a requirement that the database timezone is set to UTC.

I think the second solution would be the best, but I'm open to ideas / input from everyone else.

**Comment by misaka00251** [comment]
So in the second solution, on the client-side will it will read something like [Time-Zone offset](http://browserspy.dk/date.php) and automatically add the time?

Like, now the offset is 480 minutes, and in the database the time is stored in UTC as `2018-12-26 14:34:32`.
Now I want to edit the time, and when I jumped into the "Edit metadata" page, the date will automatically correct to `2018-12-26 22:34:32`.

**Comment by thebaer** [comment]
Right, [here](https://github.com/writeas/writefreely/blob/master/templates/edit-meta.tmpl#L283)'s where the conversion already happens on the client-side.

After a little more thought, I think this is going to be the best solution.

**Comment by thebaer** [comment]
Okay, updated the [documentation](https://writefreely.org/start) to include this requirement now. I'll make sure this makes it into other docs, too. Thanks for the report and discussion!
