### ISSUE TITLE
Question about moderation for federated AP posts

### ISSUE THREAD

**Issue by ck-slackz** [writeas/writefreely#52]
Firstly, so excited to see this functionality working, so cool!  Something I was thinking about though is adding fediverse post links that are created by write.as at the end of entries (sort of like, wanna comment? Here's the post on the fediverse!)

However something I noticed is that comments on these posts are vulnerable to spam / harassment since one can't manage the moderation aspects w/o logging into account.

Not sure how this is managed, but would it be possible to expose creds for AP account in order to manage comment deletion, blocks, etc?

Thanks again for all your work on platform! So nice to use

**Comment by thebaer** [comment]
Thanks! Really glad you like the platform :slightly_smiling_face: 

I like your use-case; that's a great way to gather comments with the current system! But as for moderation, it isn't quite that straightforward. Replies / comments aren't actually pulled in by WriteFreely/Write.as itself, so there's nothing to technically moderate on our end.

I think this is mitigated a bit by the fact most fediverse platforms you view replies through (like Mastodon), have decent per-user and per-instance moderation tools. It's not perfect, but it does give people _some_ control over what they see.

Does that answer your question? _(I'm going to close this issue since it isn't a bug, but please feel free to continue the discussion here.)_

**Comment by ck-slackz** [comment]
Makes sense, thanks!  Yeah, started to realize what was going in when trying to find a "link" to the federated posts.

Lol, ohhh, federation 101.  So used to hosted accounts.

Thanks so much for looking at this and for quick reply!
