### ISSUE TITLE
NOW doesn't exist in sqlite

### ISSUE THREAD

**Issue by geekgonecrazy** [writeas/writefreely#56]
### Describe the bug
```
ERROR: 2019/01/06 23:49:35 log.go:26: Couldn't add follower in DB: no such function: NOW
```

NOW doesn't exist in SQLite it seems in 0.6.0 its here: https://github.com/writeas/writefreely/blob/v0.6.0/activitypub.go#L401
master currently its here: https://github.com/writeas/writefreely/blob/master/activitypub.go#L411

### Steps to reproduce (if necessary)
1. Turn on debugging ( actually I don't think needed to make it show up )
2. Have someone follow your blog from mastodon or elsewhere in the fediverse

### Expected behavior
no error :)

### Application configuration
 - **Single mode or Multi-user mode?**  single
 - **Database?** sqlite
 - **Open registration?**  no
 - **Federation enabled?** no

**Version or last commit**: 0.6.0

**Comment by geekgonecrazy** [comment]
I think can switch to: `date('now')` potentially

https://www.techonthenet.com/sqlite/functions/now.php

**Comment by thebaer** [comment]
Good catch. We do have a [helper function](https://github.com/writeas/writefreely/blob/master/database.go#L126) for this -- I just must've missed this, since the query isn't in `database.go`.

I'll go ahead and fix the queries where they are, but for the future I'd say we should move them (and any others missed) over to `database.go` so everything is in one place.

**Comment by geekgonecrazy** [comment]
Ah perfect! :grin:
