### ISSUE TITLE
"Hashtags" in code blocks get parsed as hashtags

### ISSUE THREAD

**Issue by thebaer** [writeas/writefreely#6]
As reported here: https://mst3k.interlinked.me/@cadey/100673777784986480

**Comment by MCSH** [comment]
How about this idea?

instead of using regexp for replacing hashtags, using a parser that does different passes. Like this https://github.com/russross/blackfriday/blob/master/markdown.go#L405

It would be something like this:

assign last_codeblock_end = 0

start = 0
for start < len(doc):
  if start < last_codeblock_end:
    ignore everything
  else:
     check if this is a new code block
     then if not do rendering


I don't think its possible to parse it using regexp, at least not with vanilla regexp, I'm not sure how different Go's regexp is from the regular expression used in theory of computation.

Just for reference, this is the code that needs changing:
https://github.com/writeas/writefreely/blob/master/postrender.go#L33

Hope this helps.

**Comment by mrvdb** [comment]
How can we move forward here? This is probably less trivial than it looks. Some things which stood out to me:

- i would have thought md -> html conversion was a more or less 'solved problem' by now, what makes our conversion special?
- the md parser seems a modified version of https://github.com/russross/blackfriday correct?  some details on why would be helpful
- the extracttags is coming from https://github.com/kylemcc/twitter-text-go which seems to be optimized for tweet parsing. Perhaps not the best choice for extracting hashtags in general?

**Comment by JLP** [comment]
I just am trying out the 0.15.1 version of WriteFreely on paper.wf instance. It looks like the hashtags in code blocks still get treated as hashtags (e.g. if you use #include in C++ code). When I read the post via Mastodon the #include is also added to the list of tags. Should this be reopened or should I open a new issue?
