### ISSUE TITLE
MathJax does not render in draft

### ISSUE THREAD

**Issue by adrusi** [writeas/writefreely#70]
In 0.7.1, MathJax does not render equations when viewing a draft, but it does when viewing a published post.

Including the `mathjax` template in `templates/post.tmpl` fixes this.

**Comment by thebaer** [comment]
Thanks. This was left out on purpose, since the MathJax setting can be enabled / disabled on individual blogs, and drafts aren't tied to any single blog.

For example, I could have multiple blogs under one account, one blog with the setting enabled and another with it disabled. Since the software doesn't know which blog the post will end up being published to, it's kind of hard to know whether or not MathJax should be rendered in the draft.

There may be some intelligent ways we can make it work in drafts, e.g. (pseudocode):

```
if single-user-blog and mathjax-enabled
  render-mathjax()

all-blogs := get-all-blogs()
if mathjax-enabled in all-blogs
  render-mathjax()
```

We could also make MathJax a per-instance setting, instead of per-blog, which would completely simplify this. That would also fit in with the eventual goal to move MathJax out of the core platform and [into a plugin](https://discuss.write.as/t/plugin-system/259/3). But I'm open to any suggestions!

**Comment by thebaer** [comment]
Another solution might be to just support a new file extension on drafts that cause MathJax to render. So we have `.txt` to get plain text, `.md` to render Markdown, maybe `.mj` to render MathJax?

**Comment by mrvdb** [comment]
what is the downside of leaving it on, or loading on-demand?

**Comment by thebaer** [comment]
Certain reserved characters could potentially interfere with normal Markdown rendering, if I'm not mistaken.

**Comment by marek-lach** [comment]
Potentially related: #90

**Comment by thebaer** [comment]
> Potentially related: #90

I _think_ that's a separate issue, but it could be.

Either way, I'm going to close this issue since it was a deliberate design decision and a fix requires more discussion. If anyone would like to help reach a conclusion on that, we should continue this [over on the forum](https://discuss.write.as/t/mathjax-does-not-render-in-draft/657).

**Comment by Crocmagnon** [comment]
I also experienced this issue today with v0.12.0.

Since I'm on a single user instance, I'd expect my settings, including custom CSS and Mathjax to apply on my Drafts. I understand the separation of drafts and posts tied to a blog on a multi user instance but on a single user instance this doesn't make much sense IMHO.

I'm posting this here because I felt that on a single user instance it's more an issue than a feature request.
