### ISSUE TITLE
HMTL being included in post Metadata, and not scrubbed when  removed from post. 

### ISSUE THREAD

**Issue by digitalgyoza** [writeas/writefreely#83]
### Describe the bug
When using html for inserting images, video or even just centering images, the html code is being included in the metadata desriptions. This is viewable both on google search results, and posted links to sites like Mastodon. Futhermore, deleting the HTML code from the post does not remove the html text from the metadata. 

### Steps to reproduce (if necessary)
1. Publish a post with html code, within first few lines of post.
2. Click on publish
3. post link to post on site such as Mastodon. Code will show in description.

### Expected behavior
Code should be ignored and not included in metadata descriptions. 

### Application configuration
 https://write.as
 - **Federation enabled?** yes

**Version or last commit**:
https://write.as

**Comment by thebaer** [comment]
Hey, thanks for reporting this. Right now we strip out Markdown for the post descriptions, so we'll need to strip out HTML, as well.

As for the metadata not updating after the HTML has been removed, is that happening when you view the same post on sites like Mastodon? Or when you _view source_ on the post itself? If it only happens on sites like Mastodon, that's likely just because it's caching the metadata.

**Comment by digitalgyoza** [comment]
I have checked google search results again, and the html is now not present within the metadata descriptions. So it looks like google has recrawled the post and updated this.

So yes, this leaves just the Mastodon posts with the link. Even when i deleted the original Mastodon post, and then posted a new updated toot, it kept the old metadata.
________________________________

**Comment by thebaer** [comment]
Yeah, sounds like that's Mastodon caching the metadata. I'm not sure how to invalidate it, unfortunately... But I fixed this, so that won't happen anymore. The change should be deployed on Write.as within the next day.
