### ISSUE TITLE
Templates/styling discrepancies

### ISSUE THREAD

**Issue by Fastidious** [writeas/writefreely#84]
Using https://blog.lrhale.com/ as an example. If you click/press on "About," see how the font and template itself is different from the one used on the main page? Same when an entry's title is clicked/pressed. Is it possible to keep formatting and styles consistent? If so, how?

**Comment by thebaer** [comment]
There are a few issues here:

* The default styles are different between the blog index and individual blog posts (the About static page and individual posts use the same template)
  * One reason it's done this way is that we want the blog header to display differently between these two templates
* Also, the blog uses a custom stylesheet that doesn't apply the same styles to individual posts and the blog index.

As mentioned in #82, we need to refactor the CSS to be more consistent in how the post body is displayed, because there shouldn't be such a difference, and custom styling should be easier. Thanks for mentioning this

**Comment by thebaer** [comment]
Closed by #115. But let me know if there are still any discrepancies we should address, @Fastidious.
